name: ecommerce-angular-app
services:
  - name: angular-static-site
    github:
      repo: username/repo-name       # GitHub repo adresin
      branch: main                   # Deploy edilecek branch
    static_sites:
      - name: angular-site
        build_command: npm run build
        output_dir: dist/ecommerce-angular
        routes:
          - path: /*
            redirect_to: /index.html
            status: 200
    environment_slug: static
    instance_size_slug: basic-xxs
    instance_count: 1
